# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ankk98 Web Portfolio
name: Ankit Khandelwal
email: ankk98@gmail.com
description: This is web portfolio of ankk98 built with jekyll.
keywords: "Software Engineer, Python, JavaScript, Deep Learning, Startups, Versatile, Open Source"
skills: ""
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ankk98.github.io" # the base hostname & protocol for your site, e.g. http://ankk98.github.io

social:
  - title: linkedin
    url: https://www.linkedin.com/in/ankk98/
  - title: medium
    url: https://medium.com/@ankk98
  - title: twitter
    url: https://twitter.com/ankk98
  - title: github
    url: https://github.com/Ankk98

color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: pretty
