
title: Ankk98 Web Portfolio
name: Ankit Khandelwal
email: ankk98@gmail.com
description: This is web portfolio of ankk98 built with jekyll.
keywords: "Software Engineer, Python, JavaScript, Deep Learning, Startups, Versatile, Open Source"
motto: "Passionately Curious | JIIT Open Dev Circle"
baseurl: "" 
url: "http://ankk98.github.io"

social:
  - title: linkedin
    url: https://www.linkedin.com/in/ankk98/
  - title: medium
    url: https://medium.com/@ankk98
  - title: twitter
    url: https://twitter.com/ankk98
  - title: github
    url: https://github.com/Ankk98

color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: pretty
